### PR TITLE
Deleware to Delaware

### PR DESCRIPTION
**Pull request by bloveless**

### CODE REVIEW

**Comment by RyanThompson** [comment]
Good catch! It's been copied up through the versions like that lol

**Comment by bloveless** [comment]
Ha ha thanks. I’m just reading through some of the field types. I have an idea for a multiple file field type. Sound promising?

Brennon Loveless 
brennon.loveless@gmail.com

**Comment by RyanThompson** [comment]
It does!

Sent from my iPhone

On May 22, 2015, at 11:52 AM, bloveless <notifications@github.com<mailto:notifications@github.com>> wrote:

Ha ha thanks. I'm just reading through some of the field types. I have an idea for a multiple file field type. Sound promising?

Brennon Loveless ?
brennon.loveless@gmail.commailto:brennon.loveless@gmail.com

> On May 22, 2015, at 10:49 AM, Ryan Thompson <notifications@github.com<mailto:notifications@github.com>> wrote:
> 
> Good catch! It's been copied up through the versions like that lol
> 
> ## 
> 
> Reply to this email directly or view it on GitHub https://github.com/anomalylabs/state-field_type/pull/1#issuecomment-104711428.

##

**Comment by bloveless** [comment]
Perfect I'll see if I can figure it out. Maybe that can be your next video ;)

**Comment by RyanThompson** [comment]
I'll have the files module done today or tomorrow so that might help. If you use the file system as it comes in Laravel and support disks you'll be ready for use with the files module since it just extends Laravel slightly.

**Comment by bloveless** [comment]
Awesome! I'll try my hand at it this weekend then! Thanks again!

**Pull request merged**
